WebBanHangAPI/Models/SanPham.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using WebBanHangAPI.Controllers;

namespace WebBanHangAPI.Models
{
    public class SanPham
    {
        [Key]
        [StringLength(10)]
        public string IDSP { get; set; }
        [Required]
        public string TenSP { get; set; }


        [Required]
        public decimal DonGia { get; set; }

        public string Anh { get; set; }
        public DateTime NgayCapNhat { get; set; }

        public string IDMH { get; set; }
        public string IDHSX { get; set; }
        public virtual ICollection<NhapKho> NhapKhos { get; set; }

        public virtual TSDongHo TSDongHo { get; set; }
        public virtual TSDienThoai TSDienThoai { get; set; }

    }
}

WebBanHangAPI/Controllers/ControllerEmpty/ShareOutSideController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using WebBanHangAPI.GlobalVariablesWeb;
using WebBanHangAPI.Models.CookieAccout;
using WebBanHangAPI.Models.mvcModels;

namespace WebBanHangAPI.Controllers
{
    public class ShareOutSideController : Controller
    {
        // GET: ShareOutSide
        public ActionResult LoginCustomer()
        {
            ViewBag.Title = "Login customer";
            return View();
        }

        public ActionResult TrangChu()
        {
           
            return View();
        }

        [HttpPost]
        public JsonResult SetMemory(TokenAccount tk)
        {

            if (tk != null)
            {
                if (tk.Flag.Equals("cookie"))
                {

                    Session.Abandon();
                    HttpCookie cookie = new HttpCookie("AccoutCustomer");
                    cookie.HttpOnly = true;
                    HttpContext.Response.Cookies.Remove("AccoutCustomer");
                    cookie.Value = tk.AccoutToken;
                    cookie.Expires = DateTime.Now.AddDays(2);
                    HttpContext.Response.SetCookie(cookie);

                    TokenAccount tokenAccount = new TokenAccount()
                    {
                        AccoutToken = Request.Cookies.Get("AccoutCustomer").Value,
                        Flag = "cookie"
                    };
                    return Json(tokenAccount);
                }
                else if (tk.Flag.Equals("session"))
                {
                    Response.Cookies["Accout"].Expires = DateTime.Now.AddDays(-1);

                    Session["Accouts"] = tk.AccoutToken;
                    TokenAccount tokenAccount = new TokenAccount()
                    {
                        AccoutToken = Session["AccoutCustomer"].ToString(),
                        Flag = "sesstion"
                    };
                    return Json(tokenAccount);
                }

            }

            return Json(tk);

        }

        [HttpGet]
        public string GetTooken()
        {
            if (Session["AccoutCustomer"] != null)
                return Session["AccoutCustomer"].ToString();
            if (Request.Cookies["AccoutCustomer"] != null)
            {
                var value = Request.Cookies["Accout"].Value.ToString();
                return value;
            }
            return null;
        }

        [HttpGet]
        public string ResetTooken()
        {
            Session.Abandon();
            Response.Cookies["AccoutCustomer"].Expires = DateTime.Now.AddDays(-1);

            return "Thang Cong";

        }

        public ActionResult SanPham(string id)
        {
            if (id != null)
            {
                IEnumerable<mvcSanPhamHangSanXuat> sanPhamList;
                IEnumerable<mvcMathang> matHangList;

                HttpResponseMessage reponse = GlobalVariables.WebApiClient.GetAsync("SanPhams/GetFindMatHang/" + id).Result;
                HttpResponseMessage reponse2 = GlobalVariables.WebApiClient.GetAsync("MatHangs").Result;
                sanPhamList = reponse.Content.ReadAsAsync<IEnumerable<mvcSanPhamHangSanXuat>>().Result;
                matHangList = reponse2.Content.ReadAsAsync<IEnumerable<mvcMathang>>().Result;

                var hsxList = new List<mvcHangSanXuat>();
                foreach (var item in sanPhamList)
                {
                    hsxList.Add(new mvcHangSanXuat() { IDHSX = item.IDHSX, TenHSX = item.TenHSX });
                }
                var join = from pn in hsxList
                           group pn by new { pn.IDHSX, pn.TenHSX } into obGroup
                           orderby obGroup.Key.IDHSX, obGroup.Key.TenHSX
                           select new
                           {
                               IDHSX = obGroup.Key.IDHSX,
                               TenHSX = obGroup.Key.TenHSX,

                           };

                var hsxListJion = new List<mvcHangSanXuat>();
                foreach (var item in join.ToList())
                {
                    hsxListJion.Add(new mvcHangSanXuat() { IDHSX = item.IDHSX, TenHSX = item.TenHSX });
                }
                var objMultipleModels = Tuple.Create<IEnumerable<mvcSanPhamHangSanXuat>, IEnumerable<mvcMathang>, IEnumerable<mvcHangSanXuat>>
                    (sanPhamList, matHangList, hsxListJion);
                return View(objMultipleModels);
            }
            else
            {
                IEnumerable<mvcSanPhamHangSanXuat> sanPhamList;
                IEnumerable<mvcMathang> matHangList;
                HttpResponseMessage reponse = GlobalVariables.WebApiClient.GetAsync("SanPhams/GetJonSanPhamHangSanXuat").Result;
                HttpResponseMessage reponse2 = GlobalVariables.WebApiClient.GetAsync("MatHangs").Result;
                sanPhamList = reponse.Content.ReadAsAsync<IEnumerable<mvcSanPhamHangSanXuat>>().Result;
                matHangList = reponse2.Content.ReadAsAsync<IEnumerable<mvcMathang>>().Result;

                var hsxList = new List<mvcHangSanXuat>();
                foreach (var item in sanPhamList)
                {
                    hsxList.Add(new mvcHangSanXuat() { IDHSX = item.IDHSX, TenHSX = item.TenHSX });
                }
                var join = from pn in hsxList
                           group pn by new { pn.IDHSX, pn.TenHSX } into obGroup
                           orderby obGroup.Key.IDHSX, obGroup.Key.TenHSX
                           select new
                           {
                               IDHSX = obGroup.Key.IDHSX,
                               TenHSX = obGroup.Key.TenHSX,

                           };

                var hsxListJion = new List<mvcHangSanXuat>();
                foreach (var item in join.ToList())
                {
                    hsxListJion.Add(new mvcHangSanXuat() { IDHSX = item.IDHSX, TenHSX = item.TenHSX });
                }

                if(Session["numberCart"] == null)
                {
                    Session["numberCart"] = 0;
                }

                var objMultipleModels = Tuple.Create<IEnumerable<mvcSanPhamHangSanXuat>, IEnumerable<mvcMathang>, IEnumerable<mvcHangSanXuat>>
                    (sanPhamList, matHangList, hsxListJion);
                return View(objMultipleModels);
            }
        }

        public ActionResult ShowProduct(string id, string idmh)
        {

            mvcSanPhamMatHangHSX sp = null;
            mvcTSDienThoai item1 = null;
            mvcTSDongHo item2 = null;
            HttpResponseMessage reponseSP = GlobalVariables.WebApiClient.GetAsync("SanPhams/GetFindSanPhamMatHangHangSX/" + id).Result;

            HttpResponseMessage reponseDT = GlobalVariables.WebApiClient.GetAsync("TSDienThoais/GetTSSanPham/" + id).Result;
            HttpResponseMessage reponseDH = GlobalVariables.WebApiClient.GetAsync("TSDongHos/GetTSSanPham/" + id).Result;
            sp = reponseSP.Content.ReadAsAsync<mvcSanPhamMatHangHSX>().Result;
            item1 = reponseDT.Content.ReadAsAsync<mvcTSDienThoai>().Result;
            item2 = reponseDH.Content.ReadAsAsync<mvcTSDongHo>().Result;
            var objMultipleModels = Tuple.Create<mvcSanPhamMatHangHSX, mvcTSDienThoai, mvcTSDongHo>(
                                    sp, item1, item2
                                    );

            return View(objMultipleModels);

        }

        public JsonResult PushCart(mvcSanPhamCart spc)
        {
            List<mvcSanPhamCart> myList = new List<mvcSanPhamCart>();
            List<mvcSanPhamCart> myList2 = new List<mvcSanPhamCart>();
            List<mvcSanPhamCart> myList3 = new List<mvcSanPhamCart>();
            if (Session["Cart"] == null )
            {
                myList.Add(spc);
                Session["Cart"] = myList;
            }
            else
            {
                myList = (List<mvcSanPhamCart>)Session["Cart"];
                myList.Add(spc);
                Session["Cart"] = myList;

                

                myList2 = (from sp in myList
                           group sp by new { sp.IDSP, sp.Anh, sp.TenSP, sp.DonGia } into obGroup
                           orderby obGroup.Key.IDSP, obGroup.Key.TenSP, obGroup.Key.DonGia, obGroup.Key.Anh
                           select new mvcSanPhamCart()
                           {

                               IDSP = obGroup.Key.IDSP,
                               TenSP = obGroup.Key.TenSP,
                               DonGia = obGroup.Key.DonGia,
                               Anh = obGroup.Key.Anh,
                               SoLuong = obGroup.Sum(x => x.SoLuong),


                           }).ToList();

                foreach(var item in myList2)
                {
                    if (item.SoLuong > 20)
                        myList3.Add(new mvcSanPhamCart()
                        {
                            IDSP = item.IDSP,
                            TenSP = item.TenSP,
                            DonGia = item.DonGia,
                            Anh = item.Anh,
                            SoLuong = 20
                        });
                    else
                        myList3.Add(item);
                }

                var sl = 0;
                foreach (var item in myList3)
                {
                    
                    sl += item.SoLuong;
                    
                }
                Session["numberCart"] = sl;
                Session["Cart"] = myList3;

            }

            return Json(spc, JsonRequestBehavior.AllowGet);
        }
        
        public ActionResult Cart()
        {
            List<mvcSanPhamCart> myList = new List<mvcSanPhamCart>();
            
            if (Session["Cart"] != null)
            {
                myList = (List<mvcSanPhamCart>)Session["Cart"];

            }

            else

WebBanHangAPI/Views/ShareOutSide/Cart.cshtml
@model IEnumerable<WebBanHangAPI.Models.mvcModels.mvcSanPhamCart>

@{
    ViewBag.Title = "Cart";
    Layout = "~/Views/Shared/_Layout.cshtml";
    <link href="~/Scripts/Library_js/fontawesome-free-5.14.0-web/css/all.min.css" rel="stylesheet" />
    
    
}

<h2>Cart</h2>

<div class="container">

    <div style=" width: 60% ; margin: 0px auto ; background: #eae0e0 ; padding: 20px;" ; class="product">

        @foreach (var item in Model)
        {

            <div id="CartPro"  class="row" style="border-bottom: 1px solid #ffffff">
                <div class="col-md-3" style="padding: 10px;">
                    <img style="width: 150px; height: 160px;" src="@item.Anh" />
                </div>
                <div class="col-md-9">
                    <div style="margin-top: 20px;">
                        <h3>@item.TenSP</h3>
                        <h4 style="color: red">@string.Format(System.Globalization.CultureInfo.GetCultureInfo("vi-VN"), "{0:c}", item.DonGia)</h4>
                        <div id="inputQuantity">
                            <button id="plus"  style="float:left" value= @item.IDSP class="plus btn btn-default" ><i class="fas fa-plus-circle"></i></button>
                            <input class="quantity" style="float: left; text-align: center; height: 33px; border: none; background: #a9a4a4" value="@item.SoLuong" type="number" id="quantity" name="quantity" min="1" max="5" autocomplete="off" readonly />
                            <button id="minus" value= @item.IDSP ; style="float:left" class="minus btn btn-default"><i class="fas fa-minus-circle"></i></button>
                        </div>
                        <div id="btnDelete" style="margin-top: 15px; text-align: right; clear: left;">
                            <button id="remove" value= @item.IDSP class="remove btn btn-default"><i class="fas fa-trash-alt"></i></button>
                        </div>
                    </div>

                </div>

            </div>
        }
        <div>
            <h4 id="SumMoney" style="text-align: right; margin-top: 30px; color: red">
            </h4>
        </div>


    </div>

</div>

@section scripts{

    @Scripts.Render("~/bundles/jqueryval")
   

    <script>


    const formatter = new Intl.NumberFormat('de-DE', {
        style: 'currency',
        currency: 'VND',
        minimumFractionDigits: 0
    })

   const tongTien = document.getElementById('SumMoney');

    tongTien.innerHTML = "Tổng tiền: " + sum().toLocaleString('vi', { style: 'currency', currency: 'VND' });

        function sum () {
            var c = 0;
            @foreach (var item in Model)
            {
                @:c += parseInt(@item.DonGia) * parseInt(@item.SoLuong) ;
            }

            return c;
        }

        function deletePropduct() {

            var els = document.getElementsByClassName("remove");
            for (var i = 0; i < els.length; i++) {
                els[i].addEventListener('click', function (e) {
                    debugger;
                    e.preventDefault();
                    var obid = e.target.closest("#btnDelete");
                    var id = obid.children[0].value;

                    $.ajax({
                        type: "GET",
                        url: "/ShareOutSide/DeleteProduct/" + id ,

                        dataType: 'json',
                        contentType: 'application/json; charset=utf-8',
                        error: function (object) {
                            debugger
                            alert("Xoa khong thanh công")
                        },
                        success: function (result) {
                            debugger;
                           
                            var t = 0;
                            for (var i = 0; i < result.length; i++)
                                t += result[i].DonGia * result[i].SoLuong;
                            debugger;
                            tongTien.innerHTML = "Tổng tiền: " + t.toLocaleString('vi', { style: 'currency', currency: 'VND' });
                            e.target.closest('#CartPro').remove();
                            NumberCart();
                        }
                    });

                    
                   
                });
            }

        }

        deletePropduct();
     

       
        function plus() {
           
            var els = document.getElementsByClassName("plus");

            for (var i = 0; i < els.length; i++) {
               
                els[i].addEventListener('click', function (e) {
                    debugger;
                    e.preventDefault();
                    var object2 = e.target.closest("#inputQuantity").children[0];
                    var id = object2.value;
                    debugger
                    var object = e.target.closest("#inputQuantity").children[1];

                    object.readOnly = true;
                    if (object.value >= 20 )
                        return;

                    var c = parseInt(object.value);

                    object.value = c + 1;
                    $.ajax({
                        type: "GET",
                        url: "/ShareOutSide/EditCart/" + id + "/?" + "value=" + object.value  ,
                       
                        dataType: 'json',
                        contentType: 'application/json; charset=utf-8',
                        error: function (object) {
                            debugger
                            alert("them khong thanh công")
                        },
                        success: function (result) {
                            debugger;
                            var t = 0;
                            for (var i = 0; i < result.length; i++)
                                t += result[i].DonGia * result[i].SoLuong;
                            debugger;
                            tongTien.innerHTML = "Tổng tiền: " + t.toLocaleString('vi', { style: 'currency', currency: 'VND' });
                            NumberCart();
                        }
                    });
                    e.preventDefault();
                    debugger;                   
                });
            }
        }

        plus();

        function minus() {
            var els = document.getElementsByClassName("minus");

            for (var i = 0; i < els.length; i++) {


                els[i].addEventListener('click', function (e) {
                    debugger;
                    e.preventDefault();
                    var object2 = e.target.closest("#inputQuantity").children[2];
                    var id = object2.value;
                    debugger
                    var object = e.target.closest("#inputQuantity").children[1];

                    object.readOnly = true;
                    if (object.value <= 1)
                        return;

                    var c = parseInt(object.value);

                    object.value = c - 1;

                    $.ajax({
                        type: "GET",
                        url: "/ShareOutSide/EditCart/" + id + "/?" + "value=" + object.value,

                        dataType: 'json',
                        contentType: 'application/json; charset=utf-8',
                        error: function (object) {
                            debugger
                            alert("Bot khong thanh công")
                        },
                        success: function (result) {
                            var t = 0;
                            for (var i = 0; i < result.length; i++)
                                t += result[i].DonGia * result[i].SoLuong;
                            tongTien.innerHTML = "Tổng tiền: " + t.toLocaleString('vi', { style: 'currency', currency: 'VND' });
                            NumberCart();
                        }
                    });
                   
                    debugger;
                });
            }
        }

            minus();

        function NumberCart() {
            $.ajax({

                type: "GET",
                url: "/ShareOutSide/NumberCart",
                dataType: 'json',
                contentType: 'application/json; charset=utf-8',
                error: function (object) {
                    alert("Loi")
                },
                success: function (result) {
                    numberCart.innerHTML = result;

                }

            });


        }

        NumberCart();
        const numberCart = document.getElementById('numbercart');

    </script>

   
}

WebBanHangAPI/Views/ShareOutSide/DisPlayCart.cshtml
@{
    ViewBag.Title = "DisPlayCart";
    Layout = "~/Views/Shared/_Layout.cshtml";

    <link href="~/Scripts/Library_js/fontawesome-free-5.14.0-web/css/all.css" rel="stylesheet" />
    <link href="~/Content/MyCss/Cart.css" rel="stylesheet" />
}

<h2 class="text-center"><i class="fas fa-cart-arrow-down"></i></h2>
<div class="container">
    <table id="cart" class="table table-hover table-condensed">
        <thead>
            <tr>
                <th style="width:50%">Tên sản phẩm</th>
                <th style="width:10%">Giá</th>
                <th style="width:8%">Số lượng</th>
                <th style="width:22%" class="text-center">Thành tiền</th>
                <th style="width:10%"> </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td data-th="Product">
                    <div class="row">
                        <div class="col-sm-2 hidden-xs">
                            <img src="http://hocwebgiare.com/thiet_ke_web_chuan_demo/shopping_cart/images/090.jpg" alt="Sản phẩm 1" class="img-responsive" width="100">
                        </div>
                        <div class="col-sm-10">
                            <h4 class="nomargin">Sản phẩm 1</h4>
                            <p>Mô tả của sản phẩm 1</p>
                        </div>
                    </div>
                </td>
                <td data-th="Price">200.000 đ</td>
                <td data-th="Quantity">
                    <input class="form-control text-center" value="1" type="number">
                </td>
                <td data-th="Subtotal" class="text-center">200.000 đ</td>
                <td class="actions" data-th="">
                    <button class="btn btn-info btn-sm">
                        <i class="fa fa-edit"></i>
                    </button>
                    <button class="btn btn-danger btn-sm">
                        <i class="fa fa-trash-o"></i>
                    </button>
                </td>
            </tr>
            <tr>
                <td data-th="Product">
                    <div class="row">
                        <div class="col-sm-2 hidden-xs">
                            <img src="http://hocwebgiare.com/thiet_ke_web_chuan_demo/shopping_cart/images/174.jpg" alt="Sản phẩm 1" class="img-responsive" width="100">
                        </div>
                        <div class="col-sm-10">
                            <h4 class="nomargin">Sản phẩm 2</h4>
                            <p>Mô tả của sản phẩm 2</p>
                        </div>
                    </div>
                </td>
                <td data-th="Price">300.000 đ</td>
                <td data-th="Quantity">
                    <input class="form-control text-center" value="1" type="number">
                </td>
                <td data-th="Subtotal" class="text-center">300.000 đ</td>
                <td class="actions" data-th="">
                    <button class="btn btn-info btn-sm">
                        <i class="fa fa-edit"></i>
                    </button>
                    <button class="btn btn-danger btn-sm">
                        <i class="fa fa-trash-o"></i>
                    </button>
                </td>
            </tr>
        </tbody>
        <tfoot>
            <tr class="visible-xs">
                <td class="text-center">
                    <strong>Tổng 200.000 đ</strong>
                </td>
            </tr>
            <tr>
                <td>
                    <a href="http://hocwebgiare.com/" class="btn btn-warning"><i class="fa fa-angle-left"></i> Tiếp tục mua hàng</a>
                </td>
                <td colspan="2" class="hidden-xs"> </td>
                <td class="hidden-xs text-center">
                    <strong>Tổng tiền 500.000 đ</strong>
                </td>
                <td>
                    <a href="http://hocwebgiare.com/" class="btn btn-success btn-block">Thanh toán <i class="fa fa-angle-right"></i></a>
                </td>
            </tr>
        </tfoot>
    </table>
</div>

WebBanHangAPI/Views/ShareOutSide/LoginCustomer.cshtml
@{
    ViewBag.Title = "LoginCustomer";
    Layout = "~/Views/Shared/LoginPage.cshtml";

}


<div class="container">
    <div class="login">
        <div class="login-header">
            <h1>Login</h1>
        </div>
        <div class="login-input">
            <i class="fas fa-user"></i>User Name
            <input class="required validate-username" id="txtUserName" type="text" placeholder="User Name" autocomplete="off" />
            <i class="fas fa-unlock-alt"></i>PassWord
            <input id="txtPassword" class="required validate-password" type="password" placeholder="PassWord" autocomplete="off" />

            <span>
                <input id="cbxRemember" type="checkbox" checked="checked" name="Remember"> Remember me ?
            </span>
            <span id="cbxPassword">
                <input id="cbxPassWord" type="checkbox" name="Remember"> Show password ?
            </span>
        </div>
        <div class="login-button">
            <button id="btnLogin" data-url="@Url.Action("TrangChu", "ShareOutSide")">Login</button>
            <span class="icon-login">
                <i class="fas fa-spinner fa-spin fa-3x"></i>
            </span>
            <span class="iput-create"><a href="Registor.html"><i class="fas fa-arrow-circle-right"></i> Creat User Login ?</a></span>
        </div>
    </div>
    <div class="modal">

    </div>
    <div class="dialog-error">
        <div>
            <h4><i class="fas fa-exclamation-circle"></i>Password error !!!!</h4>
        </div>
        <div>
            <button id="btnDialogClose">Close</button>

        </div>

    </div>

</div>


<script src="~/Scripts/Library_js/Jquery/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/MyJavascript/LoginCustomer.js"></script>

WebBanHangAPI/Views/ShareOutSide/TrangChu.cshtml
@{
    ViewBag.Title = "TrangChu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>TrangChu</h2>